import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Cursor from "@/ui/Cursor";
import { LenisProvider } from "@/utils/LenisContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bhavya Dhanwani",
  description: "Generated by create next app",
  verification: {
    google: "_oiJ54jEgwZvkUAvDC2-23EfP3dSIdB5776iXVANBiI",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Cursor />
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
